quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_Sy9mBezT2xEb
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-tiny-butterfly-aexqisfp-pooler.c-2.us-east-2.aws.neon.tech:5432/neondb?sslmode=require

quarkus.hibernate-orm.packages=br.com.checklist.entity